"""Git PR workflow: commit, push, and create pull requests."""

from __future__ import annotations

import asyncio
import shutil
from pathlib import Path
from typing import Any

from pydantic import BaseModel


class PRResult(BaseModel):
    """Result of a PR creation attempt."""

    success: bool
    branch: str = ""
    remote: str = ""
    pr_url: str = ""
    description: str = ""
    error: str = ""


async def _run(cmd: list[str], cwd: Path, timeout: int = 60) -> tuple[int, str, str]:
    """Run a subprocess and return (returncode, stdout, stderr)."""
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=str(cwd),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    return (
        proc.returncode or 0,
        stdout.decode(errors="replace"),
        stderr.decode(errors="replace"),
    )


async def get_branch_info(workspace: Path) -> dict[str, str]:
    """Get current branch, remote, and base branch info."""
    rc, branch, _ = await _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], workspace)
    branch = branch.strip() if rc == 0 else ""

    rc, remote_url, _ = await _run(["git", "remote", "get-url", "origin"], workspace)
    remote_url = remote_url.strip() if rc == 0 else ""

    # Detect default branch.
    rc, head_ref, _ = await _run(
        ["git", "symbolic-ref", "refs/remotes/origin/HEAD"], workspace
    )
    base = head_ref.strip().removeprefix("refs/remotes/origin/") if rc == 0 else "main"

    return {"branch": branch, "remote": remote_url, "base": base}


async def get_diff_summary(workspace: Path) -> str:
    """Get a summary of changes for PR description generation."""
    rc, stat, _ = await _run(["git", "diff", "--stat", "HEAD~1"], workspace)
    if rc != 0:
        # Fallback: diff against base.
        info = await get_branch_info(workspace)
        rc, stat, _ = await _run(
            ["git", "diff", "--stat", f"origin/{info['base']}...HEAD"], workspace
        )
    return stat.strip() if rc == 0 else ""


async def get_commit_messages(workspace: Path, limit: int = 10) -> list[str]:
    """Get recent commit messages on this branch."""
    rc, log, _ = await _run(
        ["git", "log", "--oneline", f"-{limit}", "--no-decorate"], workspace
    )
    if rc != 0:
        return []
    return [line.strip() for line in log.splitlines() if line.strip()]


def generate_pr_description(
    branch: str,
    base: str,
    commits: list[str],
    diff_stat: str,
) -> str:
    """Generate a structured PR description from branch info."""
    title = branch.removeprefix("nooa-coding/").replace("-", " ").title()
    if len(title) > 72:
        title = title[:69] + "..."

    lines = ["## Summary\n"]
    if commits:
        lines.append("### Commits\n")
        for msg in commits:
            lines.append(f"- {msg}")
        lines.append("")

    if diff_stat:
        lines.append("### Changes\n")
        lines.append(f"```\n{diff_stat}\n```")
        lines.append("")

    lines.append("---")
    lines.append(f"*Branch: `{branch}` → `{base}`*")
    lines.append("*Generated by nooa-coding*")

    return "\n".join(lines)


async def push_branch(workspace: Path, *, force: bool = False) -> tuple[bool, str]:
    """Push the current branch to origin. Returns (success, message)."""
    info = await get_branch_info(workspace)
    branch = info["branch"]
    if not branch:
        return False, "Could not determine current branch"

    cmd = ["git", "push", "origin", branch]
    if force:
        cmd.insert(2, "--force-with-lease")

    rc, stdout, stderr = await _run(cmd, workspace, timeout=120)
    if rc != 0:
        return False, f"Push failed: {stderr.strip() or stdout.strip()}"
    return True, f"Pushed {branch} to origin"


async def create_pr_gh(
    workspace: Path,
    *,
    title: str = "",
    body: str = "",
    base: str = "",
    draft: bool = False,
) -> PRResult:
    """Create a PR using the GitHub CLI (gh)."""
    gh = shutil.which("gh")
    if not gh:
        return PRResult(
            success=False,
            error="GitHub CLI (gh) not found. Install it: https://cli.github.com/",
        )

    info = await get_branch_info(workspace)
    branch = info["branch"]
    base = base or info["base"]

    if not title:
        commits = await get_commit_messages(workspace, limit=1)
        title = commits[0].split(" ", 1)[-1] if commits else branch

    if not body:
        commits = await get_commit_messages(workspace)
        diff_stat = await get_diff_summary(workspace)
        body = generate_pr_description(branch, base, commits, diff_stat)

    cmd = [gh, "pr", "create", "--title", title, "--body", body, "--base", base]
    if draft:
        cmd.append("--draft")

    rc, stdout, stderr = await _run(cmd, workspace, timeout=60)
    if rc != 0:
        return PRResult(
            success=False,
            branch=branch,
            error=f"gh pr create failed: {stderr.strip() or stdout.strip()}",
        )

    pr_url = stdout.strip()
    return PRResult(
        success=True,
        branch=branch,
        remote=info["remote"],
        pr_url=pr_url,
        description=body,
    )


async def prepare_and_create_pr(
    workspace: Path,
    *,
    title: str = "",
    draft: bool = False,
    llm: Any = None,
) -> PRResult:
    """Full PR workflow: ensure committed, push, create PR.

    If an LLM is provided, uses it to generate a better PR description.
    """
    # Check for uncommitted changes.
    rc, status, _ = await _run(["git", "status", "--porcelain"], workspace)
    if rc == 0 and status.strip():
        return PRResult(
            success=False,
            error="Uncommitted changes detected. Commit or stash them first.",
        )

    # Push the branch.
    pushed, push_msg = await push_branch(workspace)
    if not pushed:
        return PRResult(success=False, error=push_msg)

    info = await get_branch_info(workspace)
    branch = info["branch"]
    base = info["base"]
    commits = await get_commit_messages(workspace)
    diff_stat = await get_diff_summary(workspace)

    # Generate description, optionally enhanced by LLM.
    body = generate_pr_description(branch, base, commits, diff_stat)
    if llm is not None:
        try:
            enhance_prompt = (
                "You are writing a GitHub pull request description.\n"
                f"Branch: {branch} → {base}\n"
                f"Commits:\n" + "\n".join(f"- {c}" for c in commits) + "\n\n"
                f"Diff stat:\n{diff_stat}\n\n"
                "Write a concise, professional PR description in markdown.\n"
                "Include: ## Summary, ## Changes (bullet list), ## Testing.\n"
                "Keep it under 30 lines. Output ONLY the markdown."
            )
            response = await llm.acall([{"role": "user", "content": enhance_prompt}])
            if response.content:
                body = response.content
        except Exception:
            pass  # Fall back to template description.

    if not title:
        title = commits[0].split(" ", 1)[-1] if commits else branch

    return await create_pr_gh(workspace, title=title, body=body, base=base, draft=draft)


__all__ = [
    "PRResult",
    "create_pr_gh",
    "generate_pr_description",
    "get_branch_info",
    "prepare_and_create_pr",
    "push_branch",
]
